#!/bin/bash
QUERY="$(echo '' | dmenu -p 'Type your search query here... ')"
[ "$QUERY" == '' ] && exit 0

QUERY="${QUERY// /%20}"

SEARCH_ENGINE="https://searx.be/search?q="
URL="${SEARCH_ENGINE}${QUERY}"

echo "$URL"
web "$URL"
