#!/bin/bash

_dir="$1"

. "$(dirname "$0")/script_common.lib.sh" || exit 1

[ "$(id -u)" = "0" ] || error "please run this script as root."

[ "$1" = "" ] && {
	warn "dir not specified, defaulting to \".\""
	_dir="."
}
[ -e "$_dir" ] || error "\"$_dir\": dir not found!"

info "running busybox httpd on dir \"$_dir\", press CTRL-C to exit."
busybox httpd -fvvv -h "$_dir"
